blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = "blog"

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("feed/", LatestPostFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')

]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super(PublishedManager, self).get_queryset().filter(status="published")


# Create your models here.
class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()

    STATUS_CHOICE = (("draft", "Draft"), ("published", "Published"))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default="draft")
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)

    def __str__(self) -> str:
        return str(self.title)

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from .models import Post
from taggit.models import Tag
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank,
    TrigramSimilarity,
)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 4
    template_name = "blog/post/list.html"

    def get_queryset(self) -> QuerySet[Any]:
        tag_slug = self.kwargs.get("tag_slug")
        qs = super().get_queryset()

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            return qs.filter(tags__in=[tag])
        return qs


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
            "similar_posts": similar_posts,
        },
    )


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False
    print("aqui")
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recomends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\`s comments: {cd['comments']}"
            send_mail(subject, message, "admin@myblog.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            search_vector = SearchVector("title", weight="A") + SearchVector(
                "body", weight="B"
            )
            search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    similarity=TrigramSimilarity("title", query),
                    rank=SearchRank(search_vector, search_query),
                )
                .filter(rank__gte=0.1)
                .order_by("-similarity")
            )
    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" type='text/css' href="{% static 'css/blog.css' %}">
</head>

<body>
        
    <nav class="navbar navbar-expand-lg navbar-light bg-color">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/logo.png' %}" alt="Image not found" width="50" height="50">
            </a>
            <a class="navbar-brand" href="{% url 'blog:post_list' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    
    <main class="container mt-4 main-content">
        {% block content %}
        {% endblock content %}
    </main>


    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<h1>{{post.title}}</h1>
<div class="row">
    <div class="col-3">
        <p class="date">
            Published {{post.publish}} by {{post.author}}
        </p>
    </div>
    <div class="col">
        {% with post.tags.all as all_tags %}
        {% if all_tags.count > 0 %}
        {% for tag in all_tags %}
        <a class="badge rounded-pill bg-primary text-decoration-none"
            href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
</div>
{{ post.body|markdown }}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share this post
    </a>
</p>

<hr>
<h2>Similar Posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

<hr>

{% with comments.count as total_comments %}
<h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks}}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
<h2>Your comment hs been added.</h2>
{% else %}
<h2>Sdd a new Comment</h2>
<form method="post">
    {{ comment_form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary mb-4">Add comment</button>
</form>
{% endif %}

{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %} My blog {% endblock title %}

{% block content %}
<div class="row">

    <aside class="col-md-4">
        <div class="p-3 mb-3 profile rounded h-100">
            <div class="text-center">
                <img src="{% static 'images/profile.png' %}" alt="Profile Image" class="img-fluid rounded-circle mb-3"
                    style="width: 150px; height: 150px;">
                <h2>Nome da Pessoa</h2>
                <p>{% lorem %}</p>

                <a href="{% url 'blog:post_feed' %}" class="text-dark me-2">
                    <i class="fa fa-rss" aria-hidden="true" style="font-size: 24px;"></i></a>

                <a href="https://www.linkedin.com/in/diogo-silva-b849a554/" class="text-dark me-2" target="_blank"
                    rel="noopener noreferrer">
                    <i class="fa-brands fa-linkedin" style="font-size: 24px;"></i>
                </a>
                <a href="https://github.com/DiogoSantosSilva/" class="text-dark me-2" target="_blank"
                    rel="noopener noreferrer">
                    <i class="fa-brands fa-github" style="font-size: 24px;"></i>
                </a>
            </div>
        </div>
    </aside>
    <div class="col-md-8">
        <h1>Posts about books</h1>
        <div class="container p-0 main-content">
            {% for post in posts %}
            <div class="card my-2">
                <div class="row g-0">
                    <div class="col-md-4">
                        <svg class="bd-placeholder-img img-fluid rounded-start" width="100%" height="160"
                            xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image"
                            preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#868e96"></rect><text x="50%" y="50%" fill="#dee2e6"
                                dy=".3em" dx="-1em">Image</text>
                        </svg>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="link-underline-light" href="{{ post.get_absolute_url }}">
                                    {{ post.title }}
                                </a>

                                {% with post.tags.all as all_tags %}
                                {% if all_tags.count > 0 %}
                                <p class="tags mt-2">Tags:
                                    {% for tag in all_tags %}
                                    <a class="badge rounded-pill bg-primary text-decoration-none"
                                        href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                                    {% endfor %}
                                </p>
                                {% endif %}
                                {% endwith %}
                            </h5>
                            <!-- <p class="card-text">
                                {{ post.body|markdown|truncatewords:30|linebreaks }}
                            </p> -->
                            <p class="card-text"><small class="text-muted">
                                    Published: {{ post.publish }} by {{ post.author }}
                                </small></p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% include "pagination.html" with page=page_obj %}
    </div>
</div>
{% endblock content %}

blog/templates/blog/post/most_commented_posts.html
<ul>
    {% for post in most_commented_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/search.html
{% extends "blog/base.html"%}
{% load blog_tags %}
{% load crispy_forms_tags %}

{% block title %}Search{% endblock title %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{query}}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result {{ total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h4>
            {{post.body|markdown|truncatewords_html:5}}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form|crispy}}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Share a post{% endblock title %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{post.title}}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="{% url 'blog:post_share' post.id %}" method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    {% endif %}
{% endblock content %}

blog/templates/pagination.html
<nav aria-label="...">
    <ul class="pagination mb-0">
        {% if page.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
        {% endif %}

        {% for number in page.paginator.page_range %}
            {% if number == page.number %}
                <li class="page-item active">
                    <span class="page-link">{{ number }}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ number }}">{{ number }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
        {% endif %}
    </ul>
</nav>